language: node_js
node_js:
  - "0.12"
  - "4"
before_install:
  - "npm i -g npm"
script: "npm test"
after_script:
  - "npm run cov"
  - "cat ./coverage/lcov.info | ./node_modules/.bin/coveralls"
notifications:
  email: false
